### PR TITLE
content: move working group content from confluence to gh

### PR DESCRIPTION
**Pull request by barbosa**
Making our content about Working Groups public 

giphy

### CODE REVIEW

**Review by luizguilhermefr — APPROVED** [review]
🚀 

Fixes #23

**Review by gustahrodrigues — APPROVED** [review]
Great! I thought it was public already :sweat_smile:

Maybe we should delete the [Confluence page](https://loadsmart.atlassian.net/wiki/spaces/engineering/pages/1878130703/Working+Groups) and have only this as a source of truth for WG definitions.

**Comment by barbosa** [comment]
> Great! I thought it was public already 😅
> 
> Maybe we should delete the [Confluence page](https://loadsmart.atlassian.net/wiki/spaces/engineering/pages/1878130703/Working+Groups) and have only this as a source of truth for WG definitions.

Absolutely! Will delete it as soon as this PR is merged.

**Review by rcmachado — APPROVED** [review]
Great!

**Comment by barbosa** [comment]
@rcmachado would you archive the Confluence page?

**Pull request merged**
